<?php

/**
 * officers-portal/settings.php
 * Officer Profile Settings — Officers Portal
 *
 * Stack: Pure PHP 8.x (native sessions) + Bootstrap 5.3 (utility classes only).
 */

// ------------------------------------------------------------------------
// 1. SESSION SECURITY GATE
// ------------------------------------------------------------------------
session_start();

if (!isset($_SESSION['user_id']) || ($_SESSION['role'] ?? 'citizen') !== 'officer') {
    header('Location: ../login.php?action=login');
    exit;
}

require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/../pusher_config.php';

$isITOfficer = (($_SESSION['role'] ?? '') === 'it_officer');

// ------------------------------------------------------------------------
// 2. POST HANDLING — PRG pattern
// ------------------------------------------------------------------------
$errors = [];
$val_userId      = htmlspecialchars($_SESSION['user_id'] ?? '', ENT_QUOTES);
$val_name        = htmlspecialchars($_SESSION['user_name'] ?? 'Officer', ENT_QUOTES);
$val_district    = htmlspecialchars($_SESSION['district'] ?? 'Unassigned District', ENT_QUOTES);
$val_purokAddr   = htmlspecialchars($_SESSION['purok_address'] ?? '', ENT_QUOTES);
$val_mobile      = htmlspecialchars($_SESSION['mobile'] ?? '09XXXXXXXXX', ENT_QUOTES);
$val_email       = htmlspecialchars($_SESSION['email'] ?? 'officer@example.gov.ph', ENT_QUOTES);

// Config section values
$val_dbHost = DB_HOST;
$val_dbPort = DB_PORT;
$val_dbName = DB_NAME;
$val_dbUser = DB_USER;
$val_dbPass = '';
$val_pusherAppId    = PUSHER_APP_ID;
$val_pusherKey      = PUSHER_KEY;
$val_pusherSecret   = '';
$val_pusherCluster  = PUSHER_CLUSTER;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $formType = $_POST['form_type'] ?? 'profile';

    // ============================================================
    // DATABASE CONFIG UPDATE (IT Officer only)
    // ============================================================
    if ($formType === 'db_config' && $isITOfficer) {
        $newDbHost = trim((string) ($_POST['db_host'] ?? ''));
        $newDbPort = trim((string) ($_POST['db_port'] ?? ''));
        $newDbName = trim((string) ($_POST['db_name'] ?? ''));
        $newDbUser = trim((string) ($_POST['db_user'] ?? ''));
        $newDbPass = (string) ($_POST['db_pass'] ?? '');

        if ($newDbHost === '') $errors['db_host'] = 'Database host is required.';
        if ($newDbPort === '' || !ctype_digit($newDbPort)) $errors['db_port'] = 'Valid port number is required.';
        if ($newDbName === '') $errors['db_name'] = 'Database name is required.';
        if ($newDbUser === '') $errors['db_user'] = 'Database username is required.';

        if (empty($errors)) {
            $configContent = "<?php\n/**\n * db_settings.php\n * Database Configuration — Auto-generated by Settings page.\n *\n * Updated: " . date('Y-m-d H:i:s') . "\n */\n\n"
                . "define('DB_HOST', " . var_export($newDbHost, true) . ");\n"
                . "define('DB_PORT', " . var_export($newDbPort, true) . ");\n"
                . "define('DB_NAME', " . var_export($newDbName, true) . ");\n"
                . "define('DB_USER', " . var_export($newDbUser, true) . ");\n"
                . "define('DB_PASS', " . var_export($newDbPass, true) . ");\n";

            if (file_put_contents(__DIR__ . '/../db_settings.php', $configContent) !== false) {
                $_SESSION['flash_msg']  = 'Database configuration saved. Changes take effect on next page load.';
                $_SESSION['flash_type'] = 'success';
            } else {
                $_SESSION['flash_msg']  = 'Failed to write database configuration file.';
                $_SESSION['flash_type'] = 'danger';
            }
            header('Location: settings.php?tab=config');
            exit;
        }

        $val_dbHost = htmlspecialchars($newDbHost, ENT_QUOTES);
        $val_dbPort = htmlspecialchars($newDbPort, ENT_QUOTES);
        $val_dbName = htmlspecialchars($newDbName, ENT_QUOTES);
        $val_dbUser = htmlspecialchars($newDbUser, ENT_QUOTES);
    }

    // ============================================================
    // PUSHER CONFIG UPDATE (IT Officer only)
    // ============================================================
    if ($formType === 'pusher_config' && $isITOfficer) {
        $newAppId   = trim((string) ($_POST['pusher_app_id'] ?? ''));
        $newKey     = trim((string) ($_POST['pusher_key'] ?? ''));
        $newSecret  = (string) ($_POST['pusher_secret'] ?? '');
        $newCluster = trim((string) ($_POST['pusher_cluster'] ?? ''));

        if ($newAppId === '') $errors['pusher_app_id'] = 'Pusher App ID is required.';
        if ($newKey === '') $errors['pusher_key'] = 'Pusher Key is required.';
        if ($newCluster === '') $errors['pusher_cluster'] = 'Pusher Cluster is required.';

        if (empty($errors)) {
            $configContent = "<?php\n/**\n * pusher_config.php\n * Pusher Real-Time Configuration — Auto-generated by Settings page.\n *\n * Updated: " . date('Y-m-d H:i:s') . "\n */\n\n"
                . "define('PUSHER_APP_ID',  " . var_export($newAppId, true) . ");\n"
                . "define('PUSHER_KEY',     " . var_export($newKey, true) . ");\n"
                . "define('PUSHER_SECRET',  " . var_export($newSecret, true) . ");\n"
                . "define('PUSHER_CLUSTER', " . var_export($newCluster, true) . ");\n\n"
                . "define('PUSHER_CHANNEL_PREFIX', 'barangay-pulpogan');\n";

            if (file_put_contents(__DIR__ . '/../pusher_config.php', $configContent) !== false) {
                $_SESSION['flash_msg']  = 'Pusher configuration saved successfully.';
                $_SESSION['flash_type'] = 'success';
            } else {
                $_SESSION['flash_msg']  = 'Failed to write Pusher configuration file.';
                $_SESSION['flash_type'] = 'danger';
            }
            header('Location: settings.php?tab=config');
            exit;
        }

        $val_pusherAppId    = htmlspecialchars($newAppId, ENT_QUOTES);
        $val_pusherKey      = htmlspecialchars($newKey, ENT_QUOTES);
        $val_pusherCluster  = htmlspecialchars($newCluster, ENT_QUOTES);
    }

    // ============================================================
    // PROFILE UPDATE
    // ============================================================
    if ($formType === 'profile') {
    $newName         = trim((string) ($_POST['full_name'] ?? ''));
    $newDistrict     = trim((string) ($_POST['district'] ?? ''));
    $newPurokAddress = trim((string) ($_POST['purok_address'] ?? ''));
    $newMobile       = trim((string) ($_POST['mobile'] ?? ''));
    $newEmail        = trim((string) ($_POST['email'] ?? ''));

    if ($newName === '' || mb_strlen($newName, 'UTF-8') < 2) {
        $errors['full_name'] = 'Please enter your full name (min. 2 characters).';
    }
    if ($newDistrict === '') {
        $errors['district'] = 'Please select your district.';
    }
    if ($newPurokAddress === '' || mb_strlen($newPurokAddress, 'UTF-8') < 3) {
        $errors['purok_address'] = 'Please enter your purok or street address (min. 3 characters).';
    }
    if (!preg_match('/^09[0-9]{9}$/', $newMobile) && !preg_match('/^\+63[0-9]{10}$/', $newMobile)) {
        $errors['mobile'] = 'Enter a valid Philippine mobile number (09XXXXXXXXX).';
    }
    if (!filter_var($newEmail, FILTER_VALIDATE_EMAIL)) {
        $errors['email'] = 'Please enter a valid email address.';
    }

    if (empty($errors)) {
        try {
            $pdo  = getDB();
            $stmt = $pdo->prepare(
                'UPDATE residents
                 SET full_name = :name, district = :district, purok_address = :purok_address,
                     mobile = :mobile, email = :email
                 WHERE id = :id'
            );
            $stmt->execute([
                ':name'          => $newName,
                ':district'      => $newDistrict,
                ':purok_address' => $newPurokAddress,
                ':mobile'        => $newMobile,
                ':email'         => $newEmail,
                ':id'            => $_SESSION['user_id'],
            ]);

            $_SESSION['user_name']     = $newName;
            $_SESSION['district']      = $newDistrict;
            $_SESSION['purok_address'] = $newPurokAddress;
            $_SESSION['mobile']        = $newMobile;
            $_SESSION['email']         = $newEmail;

            $_SESSION['flash_msg']  = 'Profile updated successfully.';
            $_SESSION['flash_type'] = 'success';
            header('Location: settings.php?success=1');
            exit;

        } catch (Throwable $e) {
            error_log('[OFFICER_SETTINGS_ERROR] ' . date('Y-m-d H:i:s') . ' — ' . $e->getMessage());
            $errors['general'] = 'Failed to save changes. Please try again.';
        }
    }

    if (!empty($errors)) {
        $val_name      = htmlspecialchars($newName, ENT_QUOTES);
        $val_district  = htmlspecialchars($newDistrict, ENT_QUOTES);
        $val_purokAddr = htmlspecialchars($newPurokAddress, ENT_QUOTES);
        $val_mobile    = htmlspecialchars($newMobile, ENT_QUOTES);
        $val_email     = htmlspecialchars($newEmail, ENT_QUOTES);
        $_SESSION['settings_errors'] = $errors;
        $_SESSION['settings_old']    = [
            'full_name'     => $newName,
            'district'      => $newDistrict,
            'purok_address' => $newPurokAddress,
            'mobile'        => $newMobile,
            'email'         => $newEmail,
        ];
        $_SESSION['flash_msg']  = 'Please correct the errors below.';
        $_SESSION['flash_type'] = 'danger';
        header('Location: settings.php?error=1');
        exit;
    }
    } // end profile form type
}

// Load flash
$submitMessage = '';
$submitSuccess = false;
if (isset($_SESSION['flash_msg'])) {
    $submitMessage = $_SESSION['flash_msg'];
    $submitSuccess = ($_SESSION['flash_type'] ?? 'danger') === 'success';
    unset($_SESSION['flash_msg'], $_SESSION['flash_type']);
}
if (isset($_SESSION['settings_errors']) && is_array($_SESSION['settings_errors'])) {
    $errors = $_SESSION['settings_errors'];
    unset($_SESSION['settings_errors']);
}
if (isset($_SESSION['settings_old']) && is_array($_SESSION['settings_old'])) {
    $val_name      = htmlspecialchars($_SESSION['settings_old']['full_name'] ?? '', ENT_QUOTES);
    $val_district  = htmlspecialchars($_SESSION['settings_old']['district'] ?? '', ENT_QUOTES);
    $val_purokAddr = htmlspecialchars($_SESSION['settings_old']['purok_address'] ?? '', ENT_QUOTES);
    $val_mobile    = htmlspecialchars($_SESSION['settings_old']['mobile'] ?? '', ENT_QUOTES);
    $val_email     = htmlspecialchars($_SESSION['settings_old']['email'] ?? '', ENT_QUOTES);
    unset($_SESSION['settings_old']);
}

$districtOptions = [
    'District 1', 'District 2', 'District 3',
    'District 4', 'District 5', 'District 6', 'District 7',
];
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Officer profile settings — Barangay Pulpogan Officers Portal.">
    <title>Settings — Barangay Pulpogan Officers Portal</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
</head>

<body class="bg-white">

    <!-- GOVPH SLIM BAR -->
    <div class="bg-light border-bottom border-secondary-subtle">
        <div class="container-fluid px-3 px-md-4">
            <div class="row py-1 small">
                <div class="col-12 col-md-6">
                    <span class="fw-bold">GOVPH</span> <span class="text-secondary">|</span> Republic of the Philippines
                </div>
                <div class="col-12 col-md-6 text-md-end text-secondary">
                    Barangay Pulpogan Officers Portal
                </div>
            </div>
        </div>
    </div>

    <!-- MAIN HEADER -->
    <header class="bg-dark text-light border-bottom border-dark">
        <div class="container-fluid px-3 px-md-4">
            <div class="row align-items-center py-3">
                <div class="col-8 col-md-10 text-center text-md-center">
                    <h1 class="h4 fw-bold text-uppercase mb-0">Barangay Pulpogan Officers Portal</h1>
                </div>
                <div class="col-4 col-md-2 d-flex justify-content-end">
                    <div class="dropdown">
                        <button class="btn p-0 border-0 bg-transparent dropdown-toggle" type="button"
                            id="avatarMenu" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-circle text-light fs-4"></i>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end rounded-1 border border-secondary-subtle" aria-labelledby="avatarMenu">
                            <li>
                                <span class="dropdown-item-text small">
                                    <span class="fw-bold"><?php echo $val_name; ?></span><br>
                                    <span class="text-secondary"><?php echo $val_district . ($val_purokAddr !== '' ? ', ' . $val_purokAddr : ''); ?></span>
                                </span>
                            </li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="index.php"><i class="bi bi-grid-3x3-gap me-2"></i>Dashboard</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item text-danger" href="index.php?action=logout"><i class="bi bi-box-arrow-right me-2"></i>Log Out</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- MAIN GRID -->
    <div class="container-fluid px-0">
        <div class="row g-0">

            <!-- SIDEBAR -->
            <nav class="col-12 col-md-3 col-lg-2 bg-light border-end border-secondary-subtle pt-4 pb-5" aria-label="Officers navigation">
                <div class="px-3 px-md-4 mb-4">
                    <span class="text-dark fw-bold small text-uppercase">
                        <i class="bi bi-shield-fill-check me-1"></i> Barangay Officer
                    </span>
                </div>
                <ul class="nav flex-column px-3 px-md-4">
                    <li class="nav-item mb-3">
                        <a href="index.php" class="nav-link p-0 text-dark text-decoration-none d-flex align-items-center border-start border-3 border-transparent ps-2">
                            <i class="bi bi-grid-3x3-gap-fill fs-3 me-3 text-dark"></i>
                            <span class="fw-bold text-uppercase small">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item mb-3">
                        <a href="verify.php" class="nav-link p-0 text-dark text-decoration-none d-flex align-items-center border-start border-3 border-transparent ps-2">
                            <i class="bi bi-check2-square fs-3 me-3 text-dark"></i>
                            <span class="fw-bold text-uppercase small">Verify Posts</span>
                        </a>
                    </li>
                    <li class="nav-item mb-3">
                        <a href="residents.php" class="nav-link p-0 text-dark text-decoration-none d-flex align-items-center border-start border-3 border-transparent ps-2">
                            <i class="bi bi-people fs-3 me-3 text-dark"></i>
                            <span class="fw-bold text-uppercase small">Residents</span>
                        </a>
                    </li>
                    <li class="nav-item mb-3">
                        <a href="announcements.php" class="nav-link p-0 text-dark text-decoration-none d-flex align-items-center border-start border-3 border-transparent ps-2">
                            <i class="bi bi-megaphone fs-3 me-3 text-dark"></i>
                            <span class="fw-bold text-uppercase small">Announcements</span>
                        </a>
                    </li>
                    <li class="nav-item mb-3">
                        <a href="settings.php" class="nav-link p-0 text-dark text-decoration-none d-flex align-items-center border-start border-3 border-dark ps-2">
                            <i class="bi bi-gear-fill fs-3 me-3 text-dark"></i>
                            <span class="fw-bold text-uppercase small">Settings</span>
                        </a>
                    </li>
                </ul>
            </nav>

            <!-- WORKSPACE -->
            <main class="col-12 col-md-9 col-lg-10 bg-white p-3 p-md-4">

                <!-- Breadcrumb -->
                <nav aria-label="Breadcrumb" class="mb-3">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.php" class="text-decoration-none">Dashboard</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Settings</li>
                    </ol>
                </nav>

                <h2 class="h5 fw-bold text-uppercase mb-1">Officer Profile Settings</h2>
                <p class="text-secondary mb-4">
                    Manage your personal information and account preferences.
                </p>

                <?php if ($submitMessage !== ''): ?>
                    <div class="alert <?php echo $submitSuccess ? 'alert-success' : 'alert-danger'; ?>
                                border border-<?php echo $submitSuccess ? 'success' : 'danger'; ?> rounded-1 py-3 mb-4" role="alert">
                        <?php if ($submitSuccess): ?>
                            <i class="bi bi-check-circle-fill me-2"></i>
                        <?php else: ?>
                            <i class="bi bi-exclamation-triangle-fill me-2"></i>
                        <?php endif; ?>
                        <?php echo htmlspecialchars($submitMessage, ENT_QUOTES); ?>
                    </div>
                <?php endif; ?>

                <?php if (isset($errors['general'])): ?>
                    <div class="alert alert-danger border border-danger rounded-1 py-3 mb-4" role="alert">
                        <i class="bi bi-exclamation-triangle-fill me-2"></i>
                        <?php echo htmlspecialchars($errors['general'], ENT_QUOTES); ?>
                    </div>
                <?php endif; ?>

                <!-- Profile Form -->
                <form method="POST" action="settings.php" novalidate>

                    <!-- Section: Personal Information -->
                    <div class="border border-secondary-subtle rounded-1 bg-white mb-4">
                        <div class="bg-light border-bottom border-secondary-subtle px-3 py-2">
                            <h3 class="h6 fw-bold mb-0">
                                <i class="bi bi-person me-2"></i>Personal Information
                            </h3>
                        </div>
                        <div class="p-3">
                            <div class="row g-3">
                                <div class="col-12 col-md-6">
                                    <label class="form-label fw-semibold">Officer ID</label>
                                    <input type="text" class="form-control py-2 rounded-1 bg-light" readonly
                                        value="<?php echo $val_userId; ?>">
                                </div>
                                <div class="col-12 col-md-6">
                                    <label for="fullName" class="form-label fw-semibold">Full Name <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control py-2 rounded-1 <?php echo isset($errors['full_name']) ? 'is-invalid' : ''; ?>"
                                        id="fullName" name="full_name"
                                        value="<?php echo $val_name; ?>"
                                        placeholder="Juan D. Dela Cruz" required>
                                    <?php if (isset($errors['full_name'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['full_name']; ?></div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-12 col-md-6">
                                    <label for="district" class="form-label fw-semibold">District <span class="text-danger">*</span></label>
                                    <select class="form-select py-2 rounded-1 <?php echo isset($errors['district']) ? 'is-invalid' : ''; ?>"
                                        id="district" name="district" required>
                                        <option value="" selected disabled>Select your district</option>
                                        <?php foreach ($districtOptions as $opt): ?>
                                            <option value="<?php echo htmlspecialchars($opt, ENT_QUOTES); ?>"
                                                <?php echo ($val_district === $opt) ? 'selected' : ''; ?>>
                                                <?php echo htmlspecialchars($opt, ENT_QUOTES); ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                    <?php if (isset($errors['district'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['district']; ?></div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-12 col-md-6">
                                    <label for="purok_address" class="form-label fw-semibold">Purok / Address <span class="text-danger">*</span></label>
                                    <input type="text"
                                        class="form-control py-2 rounded-1 <?php echo isset($errors['purok_address']) ? 'is-invalid' : ''; ?>"
                                        id="purok_address" name="purok_address"
                                        value="<?php echo $val_purokAddr; ?>"
                                        placeholder="e.g. Purok 3, Sitio Masagana"
                                        maxlength="150" required>
                                    <?php if (isset($errors['purok_address'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['purok_address']; ?></div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-12 col-md-6">
                                    <label for="mobile" class="form-label fw-semibold">Mobile Number <span class="text-danger">*</span></label>
                                    <input type="tel" class="form-control py-2 rounded-1 <?php echo isset($errors['mobile']) ? 'is-invalid' : ''; ?>"
                                        id="mobile" name="mobile"
                                        value="<?php echo $val_mobile; ?>"
                                        placeholder="09XXXXXXXXX" required>
                                    <?php if (isset($errors['mobile'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['mobile']; ?></div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-12 col-md-6">
                                    <label for="email" class="form-label fw-semibold">Email Address <span class="text-danger">*</span></label>
                                    <input type="email" class="form-control py-2 rounded-1 <?php echo isset($errors['email']) ? 'is-invalid' : ''; ?>"
                                        id="email" name="email"
                                        value="<?php echo $val_email; ?>"
                                        placeholder="officer@example.gov.ph" required>
                                    <?php if (isset($errors['email'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['email']; ?></div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Section: Account Status -->
                    <div class="border border-secondary-subtle rounded-1 bg-white mb-4">
                        <div class="bg-light border-bottom border-secondary-subtle px-3 py-2">
                            <h3 class="h6 fw-bold mb-0">
                                <i class="bi bi-shield-check me-2"></i>Account Status
                            </h3>
                        </div>
                        <div class="p-3">
                            <div class="row g-3 align-items-center">
                                <div class="col-12 col-md-6">
                                    <p class="mb-1 small text-secondary">Verification Status</p>
                                    <span class="badge bg-success rounded-1 px-2 py-1">Verified Officer</span>
                                </div>
                                <div class="col-12 col-md-6">
                                    <p class="mb-1 small text-secondary">Account Type</p>
                                    <?php if ($isITOfficer): ?>
                                        <span class="badge bg-danger rounded-1 px-2 py-1">IT Officer</span>
                                    <?php else: ?>
                                        <span class="badge bg-dark rounded-1 px-2 py-1">Barangay Officer</span>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Submit -->
                    <div class="d-flex flex-column flex-sm-row align-items-start gap-3 mb-4">
                        <button type="submit" class="btn btn-success rounded-1 py-2 px-4 fw-semibold">
                            <i class="bi bi-check-circle me-2"></i>Save Changes
                        </button>
                    </div>

                </form>

                <?php if ($isITOfficer): ?>
                <!-- ============================================================
                     IT OFFICER ONLY: SYSTEM CONFIGURATION
                     ============================================================ -->

                <!-- Section: Database Configuration -->
                <form method="POST" action="settings.php" novalidate>
                    <input type="hidden" name="form_type" value="db_config">
                    <div class="border border-secondary-subtle rounded-1 bg-white mb-4">
                        <div class="bg-light border-bottom border-secondary-subtle px-3 py-2 d-flex justify-content-between align-items-center">
                            <h3 class="h6 fw-bold mb-0">
                                <i class="bi bi-database me-2"></i>Database Configuration (MySQL)
                            </h3>
                            <span class="badge bg-dark rounded-1">IT Officer Only</span>
                        </div>
                        <div class="p-3">
                            <div class="row g-3">
                                <div class="col-12 col-md-6">
                                    <label for="dbHost" class="form-label fw-semibold">Host</label>
                                    <input type="text" class="form-control py-2 rounded-1 <?php echo isset($errors['db_host']) ? 'is-invalid' : ''; ?>"
                                        id="dbHost" name="db_host"
                                        value="<?php echo $val_dbHost; ?>" required>
                                    <?php if (isset($errors['db_host'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['db_host']; ?></div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-12 col-md-6">
                                    <label for="dbPort" class="form-label fw-semibold">Port</label>
                                    <input type="text" class="form-control py-2 rounded-1 <?php echo isset($errors['db_port']) ? 'is-invalid' : ''; ?>"
                                        id="dbPort" name="db_port"
                                        value="<?php echo $val_dbPort; ?>" required>
                                    <?php if (isset($errors['db_port'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['db_port']; ?></div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-12 col-md-6">
                                    <label for="dbName" class="form-label fw-semibold">Database Name</label>
                                    <input type="text" class="form-control py-2 rounded-1 <?php echo isset($errors['db_name']) ? 'is-invalid' : ''; ?>"
                                        id="dbName" name="db_name"
                                        value="<?php echo $val_dbName; ?>" required>
                                    <?php if (isset($errors['db_name'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['db_name']; ?></div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-12 col-md-6">
                                    <label for="dbUser" class="form-label fw-semibold">Username</label>
                                    <input type="text" class="form-control py-2 rounded-1 <?php echo isset($errors['db_user']) ? 'is-invalid' : ''; ?>"
                                        id="dbUser" name="db_user"
                                        value="<?php echo $val_dbUser; ?>" required>
                                    <?php if (isset($errors['db_user'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['db_user']; ?></div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-12">
                                    <label for="dbPass" class="form-label fw-semibold">Password</label>
                                    <input type="password" class="form-control py-2 rounded-1"
                                        id="dbPass" name="db_pass"
                                        placeholder="Leave blank to keep current password">
                                    <p class="form-text small text-secondary mb-0">Leave blank to keep the existing password.</p>
                                </div>
                            </div>
                        </div>
                        <div class="bg-light border-top border-secondary-subtle px-3 py-2">
                            <button type="submit" class="btn btn-dark rounded-1 py-1 px-3 fw-semibold small">
                                <i class="bi bi-save me-1"></i>Save Database Config
                            </button>
                        </div>
                    </div>
                </form>

                <!-- Section: Pusher Configuration -->
                <form method="POST" action="settings.php" novalidate>
                    <input type="hidden" name="form_type" value="pusher_config">
                    <div class="border border-secondary-subtle rounded-1 bg-white mb-4">
                        <div class="bg-light border-bottom border-secondary-subtle px-3 py-2 d-flex justify-content-between align-items-center">
                            <h3 class="h6 fw-bold mb-0">
                                <i class="bi bi-broadcast me-2"></i>Pusher Configuration
                            </h3>
                            <span class="badge bg-dark rounded-1">IT Officer Only</span>
                        </div>
                        <div class="p-3">
                            <div class="row g-3">
                                <div class="col-12 col-md-6">
                                    <label for="pusherAppId" class="form-label fw-semibold">App ID</label>
                                    <input type="text" class="form-control py-2 rounded-1 <?php echo isset($errors['pusher_app_id']) ? 'is-invalid' : ''; ?>"
                                        id="pusherAppId" name="pusher_app_id"
                                        value="<?php echo $val_pusherAppId; ?>" required>
                                    <?php if (isset($errors['pusher_app_id'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['pusher_app_id']; ?></div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-12 col-md-6">
                                    <label for="pusherKey" class="form-label fw-semibold">Key</label>
                                    <input type="text" class="form-control py-2 rounded-1 <?php echo isset($errors['pusher_key']) ? 'is-invalid' : ''; ?>"
                                        id="pusherKey" name="pusher_key"
                                        value="<?php echo $val_pusherKey; ?>" required>
                                    <?php if (isset($errors['pusher_key'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['pusher_key']; ?></div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-12 col-md-6">
                                    <label for="pusherSecret" class="form-label fw-semibold">Secret</label>
                                    <input type="password" class="form-control py-2 rounded-1"
                                        id="pusherSecret" name="pusher_secret"
                                        placeholder="Leave blank to keep current secret">
                                    <p class="form-text small text-secondary mb-0">Leave blank to keep the existing secret.</p>
                                </div>
                                <div class="col-12 col-md-6">
                                    <label for="pusherCluster" class="form-label fw-semibold">Cluster</label>
                                    <input type="text" class="form-control py-2 rounded-1 <?php echo isset($errors['pusher_cluster']) ? 'is-invalid' : ''; ?>"
                                        id="pusherCluster" name="pusher_cluster"
                                        value="<?php echo $val_pusherCluster; ?>" required>
                                    <?php if (isset($errors['pusher_cluster'])): ?>
                                        <div class="invalid-feedback"><?php echo $errors['pusher_cluster']; ?></div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <div class="bg-light border-top border-secondary-subtle px-3 py-2">
                            <button type="submit" class="btn btn-dark rounded-1 py-1 px-3 fw-semibold small">
                                <i class="bi bi-save me-1"></i>Save Pusher Config
                            </button>
                        </div>
                    </div>
                </form>

                <?php else: ?>
                <!-- Non-IT Officer: read-only config display -->
                <div class="border border-secondary-subtle rounded-1 bg-light mb-4">
                    <div class="px-3 py-2">
                        <h3 class="h6 fw-bold mb-0">
                            <i class="bi bi-lock me-2"></i>System Configuration
                        </h3>
                    </div>
                    <div class="p-3">
                        <p class="small text-secondary mb-0">
                            <i class="bi bi-info-circle me-1"></i>
                            Database and Pusher configuration can only be edited by an <strong>IT Officer</strong>.
                            Contact your system administrator for access.
                        </p>
                    </div>
                </div>
                <?php endif; ?>

                <!-- Data privacy -->
                <div class="border border-secondary-subtle rounded-1 bg-light p-3 mb-4">
                    <h3 class="h6 fw-bold mb-2">
                        <i class="bi bi-info-circle me-2"></i>Data Privacy Notice
                    </h3>
                    <p class="small text-secondary mb-0">
                        Your personal information is processed under the Data Privacy Act of 2012 (Republic Act 10173)
                        and is used solely for community mutual-aid coordination. Contact the Barangay Data Protection
                        Officer for any data-related concerns.
                    </p>
                </div>

                <!-- Footer -->
                <div class="border-top border-secondary-subtle pt-3">
                    <p class="small text-secondary mb-0">
                        &copy; <?php echo date('Y'); ?> Barangay Pulpogan Portal. Officers access only.
                    </p>
                </div>

            </main>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>
