<?php
/**
 * db_settings.php
 * Database Configuration — Auto-generated by Settings page.
 *
 * Edit values below or update via Officers Portal > Settings (IT Officer only).
 */

define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', 'barangay_pulpogan_bayanihan');
define('DB_USER', 'root');
define('DB_PASS', '');
